- alias: Test notification
  trigger:
    - platform: time
      hours: 22
      minutes: 00
      seconds: 00
  action:
    service: notify.notify
    data:
      message: 'test message aaaa'

- alias: 'Update Available'
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.notify
    data:
      message: 'Update for Home Assitant is Available'

  
    
 
